mutation createFileSourceUpload($fileInfo: UploadFileInfo!) {
  createFileSourceUpload(fileInfo: $fileInfo) {
    id
  }
}

mutation uploadFileSourceChunk($sourceId: String!, $file: UploadFileChunk!) {
  uploadFileSourceChunk(sourceId: $sourceId, file: $file)
}

mutation probeFileSource($sourceId: String!) {
  probeFileSource(sourceId: $sourceId)
}
