mutation createFileSourceUpload($fileInfo: UploadFileInfo!) {
  createFileSourceUpload(fileInfo: $fileInfo) {
    id
  }
}

mutation uploadFileSourceChunk($sourceId: String!, $file: UploadFileChunk!) {
  uploadFileSourceChunk(sourceId: $sourceId, file: $file)
}

mutation probeFileSource($sourceId: String!) {
  probeFileSource(sourceId: $sourceId)
}

query getFileSourcesSimple($skip: Int!, $take: Int!, $status: TranscodeStatus) {
  fileSources(skip: $skip, take: $take, status: $status) {
    total
    sources {
      id
      duration
      name
      thumbnailUrl
      status
      createdAt
    }
  }
}

query getFileSource($id: ID!) {
  fileSource(sourceId: $id) {
    duration
    name
    thumbnailUrl
    status
    createdAt
    width
    height
    error
    source {
      extension
      width
      height
      status
      fileSize
    }
  }
}
