version: "3"
services:
  app:
    build: ../../
    image: ghcr.io/horikawacsc/mitei-server/server-media:v1.0.6 
    env_file: .env
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ../../data:/app/sources
    depends_on:
      - mongo
      - redis
  rtmp:
    build: ../../nginx
    image: ghcr.io/horikawacsc/mitei-server/nginx:v1.0.6
    ports:
      - 8000:8000
      - 8001:8001
      - 1935:1935
    depends_on:
      - app
  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ../../data/redis:/data
  mongo:
    restart: always
    image: mongo:3.6
    volumes:
      - ../../data/mongo:/data/db
  mongoui:
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
