version: "3"
services:
  app:
    build: ../../
    image: horikawacsc/mitei-server
    env_file: .env
    ports:
      - 3000:3000
      - 3001:3001
    volumes:
      - ../../data:/app/data
    depends_on:
      - mongo
      - redis
  rtmp:
    build: ../../nginx
    image: horikawacsc/mitei-server-nginx
    ports:
      - 8000:8000
      - 8001:8001
      - 1935:1935
    depends_on:
      - app
  redis:
    restart: always
    image: redis:4.0-alpine
    volumes:
      - ../../redis:/data
  mongo:
    restart: always
    image: mongo:3.6
    volumes:
      - ../../mongo:/data/db
  mongoui:
    restart: always
    image: mongo-express
    ports:
      - 8081:8081
    depends_on:
      - mongo
