scalar Date

input UploadFileInfo {
  filename: String!
  size: Int!
}

input UploadFileChunk {
  chunk: Upload!
  begin: Int!
  size: Int!
}

enum TranscodeStatus {
  pending
  running
  success
  failed
}

interface SourceBase {
  id: ID!
  status: TranscodeStatus!
  duration: Float!
  thumbnailUrl: String
  width: Int!
  height: Int!
  createdAt: Date!
  updatedAt: Date!
  createdBy: User!
}

enum SourceStatus {
  uploading
  avail
  deleted
}

type FileSource implements SourceBase {
  id: ID!
  status: TranscodeStatus!
  duration: Float!
  thumbnailUrl: String
  width: Int!
  height: Int!
  createdAt: Date!
  updatedAt: Date!
  createdBy: User!

  # additional props
  name: String!
  sourceExtension: String!
  sourceStatus: SourceStatus!
  error: String
  sourceWidth: Int!
  sourceHeight: Int!
}

type FileSourceList {
  sources: [FileSource!]!
  total: Int!
}

enum UserKind {
  normal
  admin
}

enum IdPType {
  twitter
}

type User {
  id: ID!
  userId: ID!
  screenName: String!
  iconUrl: String
  kind: UserKind!
  type: IdPType!
}

type Users {
  users: [User!]!
  total: Int!
}

type Query {
  # admin func
  fileSource(sourceId: ID!): FileSource
  fileSources(status: TranscodeStatus, skip: Int, take: Int): FileSourceList!

  users(kind: UserKind, type: IdPType, skip: Int, take: Int): Users!

  # normal func
  me: User
}

type Mutation {
  # admin func
  createFileSourceUpload(fileInfo: UploadFileInfo!): FileSource!
  uploadFileSourceChunk(sourceId: String!, file: UploadFileChunk!): Boolean!
  probeFileSource(sourceId: String!): Boolean!
  transcodeFileSource(sourceId: String!): Boolean!
}

schema {
  query: Query
  mutation: Mutation
}
